### ISSUE TITLE
EDA plots now showing correctly in the initial_data_exploration file

### ISSUE THREAD

**Issue by shyan0903** [PANDASANG1231/522_Ramen#15]
Looks like the file was uploaded before everything got generated.

**Comment by datallurgy** [comment]
I think pandas-profiler doesn't display correctly on GitHub since it's interactive. I've uploaded an HTML version for review.

**Comment by PANDASANG1231** [comment]
I think that an HTML version should be fine. Thanks @datallurgy

**Comment by datallurgy** [comment]
What's going on with this issue? I thought the HTML export from the notebook resolved. @PANDASANG1231
